/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as JasaPembuatanWebsiteAplikasiLandingPageRouteImport } from './routes/jasa-pembuatan-website-aplikasi-landing-page'
import { Route as JasaPembuatanAplikasiCustomRouteImport } from './routes/jasa-pembuatan-aplikasi-custom'
import { Route as JasaDashboardBisnisRouteImport } from './routes/jasa-dashboard-bisnis'
import { Route as JasaAiAutomationBisnisRouteImport } from './routes/jasa-ai-automation-bisnis'
import { Route as CaraKerjakuMenggunakanAiRouteImport } from './routes/cara-kerjaku-menggunakan-ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InsightIndexRouteImport } from './routes/insight.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as InsightSlugRouteImport } from './routes/insight.$slug'
import { Route as ISlugRouteImport } from './routes/i.$slug'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant-chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicConsultantChatRouteImport } from './routes/api/public/consultant-chat'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated/admin.portfolio'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin.pipeline'
import { Route as AuthenticatedAdminMemoryRouteImport } from './routes/_authenticated/admin.memory'
import { Route as AuthenticatedAdminConversationsRouteImport } from './routes/_authenticated/admin.conversations'
import { Route as AuthenticatedAdminAutomationRouteImport } from './routes/_authenticated/admin.automation'
import { Route as AuthenticatedAdminAssistantRouteImport } from './routes/_authenticated/admin.assistant'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminProposalsIndexRouteImport } from './routes/_authenticated/admin.proposals.index'
import { Route as AuthenticatedAdminProjectsIndexRouteImport } from './routes/_authenticated/admin.projects.index'
import { Route as AuthenticatedAdminLeadsIndexRouteImport } from './routes/_authenticated/admin.leads.index'
import { Route as AuthenticatedAdminInvoicesIndexRouteImport } from './routes/_authenticated/admin.invoices.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as AuthenticatedAdminAssistantIndexRouteImport } from './routes/_authenticated/admin.assistant.index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramTestRouteImport } from './routes/api/public/telegram/test'
import { Route as ApiPublicPaymentsXenditRouteImport } from './routes/api/public/payments/xendit'
import { Route as ApiPublicHooksTelegramDailyBriefRouteImport } from './routes/api/public/hooks/telegram-daily-brief'
import { Route as ApiPublicHooksAutomationScanRouteImport } from './routes/api/public/hooks/automation-scan'
import { Route as AuthenticatedAdminProposalsIdRouteImport } from './routes/_authenticated/admin.proposals.$id'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin.projects.$id'
import { Route as AuthenticatedAdminLeadsIdRouteImport } from './routes/_authenticated/admin.leads.$id'
import { Route as AuthenticatedAdminInvoicesIdRouteImport } from './routes/_authenticated/admin.invoices.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedAdminAssistantThreadIdRouteImport } from './routes/_authenticated/admin.assistant.$threadId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const JasaPembuatanWebsiteAplikasiLandingPageRoute =
  JasaPembuatanWebsiteAplikasiLandingPageRouteImport.update({
    id: '/jasa-pembuatan-website-aplikasi-landing-page',
    path: '/jasa-pembuatan-website-aplikasi-landing-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const JasaPembuatanAplikasiCustomRoute =
  JasaPembuatanAplikasiCustomRouteImport.update({
    id: '/jasa-pembuatan-aplikasi-custom',
    path: '/jasa-pembuatan-aplikasi-custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const JasaDashboardBisnisRoute = JasaDashboardBisnisRouteImport.update({
  id: '/jasa-dashboard-bisnis',
  path: '/jasa-dashboard-bisnis',
  getParentRoute: () => rootRouteImport,
} as any)
const JasaAiAutomationBisnisRoute = JasaAiAutomationBisnisRouteImport.update({
  id: '/jasa-ai-automation-bisnis',
  path: '/jasa-ai-automation-bisnis',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraKerjakuMenggunakanAiRoute =
  CaraKerjakuMenggunakanAiRouteImport.update({
    id: '/cara-kerjaku-menggunakan-ai',
    path: '/cara-kerjaku-menggunakan-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightIndexRoute = InsightIndexRouteImport.update({
  id: '/insight/',
  path: '/insight/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightSlugRoute = InsightSlugRouteImport.update({
  id: '/insight/$slug',
  path: '/insight/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant-chat',
  path: '/api/assistant-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicConsultantChatRoute = ApiPublicConsultantChatRouteImport.update({
  id: '/api/public/consultant-chat',
  path: '/api/public/consultant-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMemoryRoute =
  AuthenticatedAdminMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConversationsRoute =
  AuthenticatedAdminConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAutomationRoute =
  AuthenticatedAdminAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssistantRoute =
  AuthenticatedAdminAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProposalsIndexRoute =
  AuthenticatedAdminProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsIndexRoute =
  AuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsIndexRoute =
  AuthenticatedAdminLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesIndexRoute =
  AuthenticatedAdminInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssistantIndexRoute =
  AuthenticatedAdminAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAssistantRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramTestRoute = ApiPublicTelegramTestRouteImport.update({
  id: '/api/public/telegram/test',
  path: '/api/public/telegram/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsXenditRoute = ApiPublicPaymentsXenditRouteImport.update({
  id: '/api/public/payments/xendit',
  path: '/api/public/payments/xendit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramDailyBriefRoute =
  ApiPublicHooksTelegramDailyBriefRouteImport.update({
    id: '/api/public/hooks/telegram-daily-brief',
    path: '/api/public/hooks/telegram-daily-brief',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationScanRoute =
  ApiPublicHooksAutomationScanRouteImport.update({
    id: '/api/public/hooks/automation-scan',
    path: '/api/public/hooks/automation-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminProposalsIdRoute =
  AuthenticatedAdminProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsIdRoute =
  AuthenticatedAdminLeadsIdRouteImport.update({
    id: '/leads/$id',
    path: '/leads/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesIdRoute =
  AuthenticatedAdminInvoicesIdRouteImport.update({
    id: '/invoices/$id',
    path: '/invoices/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssistantThreadIdRoute =
  AuthenticatedAdminAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAdminAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cara-kerjaku-menggunakan-ai': typeof CaraKerjakuMenggunakanAiRoute
  '/jasa-ai-automation-bisnis': typeof JasaAiAutomationBisnisRoute
  '/jasa-dashboard-bisnis': typeof JasaDashboardBisnisRoute
  '/jasa-pembuatan-aplikasi-custom': typeof JasaPembuatanAplikasiCustomRoute
  '/jasa-pembuatan-website-aplikasi-landing-page': typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/assistant-chat': typeof ApiAssistantChatRoute
  '/d/$slug': typeof DSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/insight/': typeof InsightIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/assistant': typeof AuthenticatedAdminAssistantRouteWithChildren
  '/admin/automation': typeof AuthenticatedAdminAutomationRoute
  '/admin/conversations': typeof AuthenticatedAdminConversationsRoute
  '/admin/memory': typeof AuthenticatedAdminMemoryRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/consultant-chat': typeof ApiPublicConsultantChatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/assistant/$threadId': typeof AuthenticatedAdminAssistantThreadIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/api/public/hooks/automation-scan': typeof ApiPublicHooksAutomationScanRoute
  '/api/public/hooks/telegram-daily-brief': typeof ApiPublicHooksTelegramDailyBriefRoute
  '/api/public/payments/xendit': typeof ApiPublicPaymentsXenditRoute
  '/api/public/telegram/test': typeof ApiPublicTelegramTestRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/admin/assistant/': typeof AuthenticatedAdminAssistantIndexRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/invoices/': typeof AuthenticatedAdminInvoicesIndexRoute
  '/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
  '/admin/proposals/': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cara-kerjaku-menggunakan-ai': typeof CaraKerjakuMenggunakanAiRoute
  '/jasa-ai-automation-bisnis': typeof JasaAiAutomationBisnisRoute
  '/jasa-dashboard-bisnis': typeof JasaDashboardBisnisRoute
  '/jasa-pembuatan-aplikasi-custom': typeof JasaPembuatanAplikasiCustomRoute
  '/jasa-pembuatan-website-aplikasi-landing-page': typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/assistant-chat': typeof ApiAssistantChatRoute
  '/d/$slug': typeof DSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/insight': typeof InsightIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/automation': typeof AuthenticatedAdminAutomationRoute
  '/admin/conversations': typeof AuthenticatedAdminConversationsRoute
  '/admin/memory': typeof AuthenticatedAdminMemoryRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/consultant-chat': typeof ApiPublicConsultantChatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/assistant/$threadId': typeof AuthenticatedAdminAssistantThreadIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/api/public/hooks/automation-scan': typeof ApiPublicHooksAutomationScanRoute
  '/api/public/hooks/telegram-daily-brief': typeof ApiPublicHooksTelegramDailyBriefRoute
  '/api/public/payments/xendit': typeof ApiPublicPaymentsXenditRoute
  '/api/public/telegram/test': typeof ApiPublicTelegramTestRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/admin/assistant': typeof AuthenticatedAdminAssistantIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesIndexRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cara-kerjaku-menggunakan-ai': typeof CaraKerjakuMenggunakanAiRoute
  '/jasa-ai-automation-bisnis': typeof JasaAiAutomationBisnisRoute
  '/jasa-dashboard-bisnis': typeof JasaDashboardBisnisRoute
  '/jasa-pembuatan-aplikasi-custom': typeof JasaPembuatanAplikasiCustomRoute
  '/jasa-pembuatan-website-aplikasi-landing-page': typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/assistant-chat': typeof ApiAssistantChatRoute
  '/d/$slug': typeof DSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/insight/': typeof InsightIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/assistant': typeof AuthenticatedAdminAssistantRouteWithChildren
  '/_authenticated/admin/automation': typeof AuthenticatedAdminAutomationRoute
  '/_authenticated/admin/conversations': typeof AuthenticatedAdminConversationsRoute
  '/_authenticated/admin/memory': typeof AuthenticatedAdminMemoryRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/consultant-chat': typeof ApiPublicConsultantChatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/assistant/$threadId': typeof AuthenticatedAdminAssistantThreadIdRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/_authenticated/admin/leads/$id': typeof AuthenticatedAdminLeadsIdRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/admin/proposals/$id': typeof AuthenticatedAdminProposalsIdRoute
  '/api/public/hooks/automation-scan': typeof ApiPublicHooksAutomationScanRoute
  '/api/public/hooks/telegram-daily-brief': typeof ApiPublicHooksTelegramDailyBriefRoute
  '/api/public/payments/xendit': typeof ApiPublicPaymentsXenditRoute
  '/api/public/telegram/test': typeof ApiPublicTelegramTestRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/admin/assistant/': typeof AuthenticatedAdminAssistantIndexRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/invoices/': typeof AuthenticatedAdminInvoicesIndexRoute
  '/_authenticated/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
  '/_authenticated/admin/proposals/': typeof AuthenticatedAdminProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cara-kerjaku-menggunakan-ai'
    | '/jasa-ai-automation-bisnis'
    | '/jasa-dashboard-bisnis'
    | '/jasa-pembuatan-aplikasi-custom'
    | '/jasa-pembuatan-website-aplikasi-landing-page'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/api/assistant-chat'
    | '/d/$slug'
    | '/i/$slug'
    | '/insight/$slug'
    | '/portal/$token'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/insight/'
    | '/products/'
    | '/admin/analytics'
    | '/admin/assistant'
    | '/admin/automation'
    | '/admin/conversations'
    | '/admin/memory'
    | '/admin/pipeline'
    | '/admin/portfolio'
    | '/admin/settings'
    | '/admin/team'
    | '/api/public/consultant-chat'
    | '/admin/'
    | '/admin/assistant/$threadId'
    | '/admin/clients/$id'
    | '/admin/invoices/$id'
    | '/admin/leads/$id'
    | '/admin/projects/$id'
    | '/admin/proposals/$id'
    | '/api/public/hooks/automation-scan'
    | '/api/public/hooks/telegram-daily-brief'
    | '/api/public/payments/xendit'
    | '/api/public/telegram/test'
    | '/api/public/telegram/webhook'
    | '/admin/assistant/'
    | '/admin/clients/'
    | '/admin/invoices/'
    | '/admin/leads/'
    | '/admin/projects/'
    | '/admin/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cara-kerjaku-menggunakan-ai'
    | '/jasa-ai-automation-bisnis'
    | '/jasa-dashboard-bisnis'
    | '/jasa-pembuatan-aplikasi-custom'
    | '/jasa-pembuatan-website-aplikasi-landing-page'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/assistant-chat'
    | '/d/$slug'
    | '/i/$slug'
    | '/insight/$slug'
    | '/portal/$token'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/insight'
    | '/products'
    | '/admin/analytics'
    | '/admin/automation'
    | '/admin/conversations'
    | '/admin/memory'
    | '/admin/pipeline'
    | '/admin/portfolio'
    | '/admin/settings'
    | '/admin/team'
    | '/api/public/consultant-chat'
    | '/admin'
    | '/admin/assistant/$threadId'
    | '/admin/clients/$id'
    | '/admin/invoices/$id'
    | '/admin/leads/$id'
    | '/admin/projects/$id'
    | '/admin/proposals/$id'
    | '/api/public/hooks/automation-scan'
    | '/api/public/hooks/telegram-daily-brief'
    | '/api/public/payments/xendit'
    | '/api/public/telegram/test'
    | '/api/public/telegram/webhook'
    | '/admin/assistant'
    | '/admin/clients'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/projects'
    | '/admin/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cara-kerjaku-menggunakan-ai'
    | '/jasa-ai-automation-bisnis'
    | '/jasa-dashboard-bisnis'
    | '/jasa-pembuatan-aplikasi-custom'
    | '/jasa-pembuatan-website-aplikasi-landing-page'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/api/assistant-chat'
    | '/d/$slug'
    | '/i/$slug'
    | '/insight/$slug'
    | '/portal/$token'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/insight/'
    | '/products/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/assistant'
    | '/_authenticated/admin/automation'
    | '/_authenticated/admin/conversations'
    | '/_authenticated/admin/memory'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/api/public/consultant-chat'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/assistant/$threadId'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/invoices/$id'
    | '/_authenticated/admin/leads/$id'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/admin/proposals/$id'
    | '/api/public/hooks/automation-scan'
    | '/api/public/hooks/telegram-daily-brief'
    | '/api/public/payments/xendit'
    | '/api/public/telegram/test'
    | '/api/public/telegram/webhook'
    | '/_authenticated/admin/assistant/'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/invoices/'
    | '/_authenticated/admin/leads/'
    | '/_authenticated/admin/projects/'
    | '/_authenticated/admin/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CaraKerjakuMenggunakanAiRoute: typeof CaraKerjakuMenggunakanAiRoute
  JasaAiAutomationBisnisRoute: typeof JasaAiAutomationBisnisRoute
  JasaDashboardBisnisRoute: typeof JasaDashboardBisnisRoute
  JasaPembuatanAplikasiCustomRoute: typeof JasaPembuatanAplikasiCustomRoute
  JasaPembuatanWebsiteAplikasiLandingPageRoute: typeof JasaPembuatanWebsiteAplikasiLandingPageRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  DSlugRoute: typeof DSlugRoute
  ISlugRoute: typeof ISlugRoute
  InsightSlugRoute: typeof InsightSlugRoute
  PortalTokenRoute: typeof PortalTokenRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  InsightIndexRoute: typeof InsightIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiPublicConsultantChatRoute: typeof ApiPublicConsultantChatRoute
  ApiPublicHooksAutomationScanRoute: typeof ApiPublicHooksAutomationScanRoute
  ApiPublicHooksTelegramDailyBriefRoute: typeof ApiPublicHooksTelegramDailyBriefRoute
  ApiPublicPaymentsXenditRoute: typeof ApiPublicPaymentsXenditRoute
  ApiPublicTelegramTestRoute: typeof ApiPublicTelegramTestRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jasa-pembuatan-website-aplikasi-landing-page': {
      id: '/jasa-pembuatan-website-aplikasi-landing-page'
      path: '/jasa-pembuatan-website-aplikasi-landing-page'
      fullPath: '/jasa-pembuatan-website-aplikasi-landing-page'
      preLoaderRoute: typeof JasaPembuatanWebsiteAplikasiLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jasa-pembuatan-aplikasi-custom': {
      id: '/jasa-pembuatan-aplikasi-custom'
      path: '/jasa-pembuatan-aplikasi-custom'
      fullPath: '/jasa-pembuatan-aplikasi-custom'
      preLoaderRoute: typeof JasaPembuatanAplikasiCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jasa-dashboard-bisnis': {
      id: '/jasa-dashboard-bisnis'
      path: '/jasa-dashboard-bisnis'
      fullPath: '/jasa-dashboard-bisnis'
      preLoaderRoute: typeof JasaDashboardBisnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jasa-ai-automation-bisnis': {
      id: '/jasa-ai-automation-bisnis'
      path: '/jasa-ai-automation-bisnis'
      fullPath: '/jasa-ai-automation-bisnis'
      preLoaderRoute: typeof JasaAiAutomationBisnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-kerjaku-menggunakan-ai': {
      id: '/cara-kerjaku-menggunakan-ai'
      path: '/cara-kerjaku-menggunakan-ai'
      fullPath: '/cara-kerjaku-menggunakan-ai'
      preLoaderRoute: typeof CaraKerjakuMenggunakanAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/': {
      id: '/insight/'
      path: '/insight'
      fullPath: '/insight/'
      preLoaderRoute: typeof InsightIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/$slug': {
      id: '/insight/$slug'
      path: '/insight/$slug'
      fullPath: '/insight/$slug'
      preLoaderRoute: typeof InsightSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant-chat': {
      id: '/api/assistant-chat'
      path: '/api/assistant-chat'
      fullPath: '/api/assistant-chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/consultant-chat': {
      id: '/api/public/consultant-chat'
      path: '/api/public/consultant-chat'
      fullPath: '/api/public/consultant-chat'
      preLoaderRoute: typeof ApiPublicConsultantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/memory': {
      id: '/_authenticated/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AuthenticatedAdminMemoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/conversations': {
      id: '/_authenticated/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AuthenticatedAdminConversationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automation': {
      id: '/_authenticated/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AuthenticatedAdminAutomationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assistant': {
      id: '/_authenticated/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AuthenticatedAdminAssistantRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proposals/': {
      id: '/_authenticated/admin/proposals/'
      path: '/proposals'
      fullPath: '/admin/proposals/'
      preLoaderRoute: typeof AuthenticatedAdminProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/': {
      id: '/_authenticated/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices/': {
      id: '/_authenticated/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assistant/': {
      id: '/_authenticated/admin/assistant/'
      path: '/'
      fullPath: '/admin/assistant/'
      preLoaderRoute: typeof AuthenticatedAdminAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAssistantRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/test': {
      id: '/api/public/telegram/test'
      path: '/api/public/telegram/test'
      fullPath: '/api/public/telegram/test'
      preLoaderRoute: typeof ApiPublicTelegramTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/xendit': {
      id: '/api/public/payments/xendit'
      path: '/api/public/payments/xendit'
      fullPath: '/api/public/payments/xendit'
      preLoaderRoute: typeof ApiPublicPaymentsXenditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-daily-brief': {
      id: '/api/public/hooks/telegram-daily-brief'
      path: '/api/public/hooks/telegram-daily-brief'
      fullPath: '/api/public/hooks/telegram-daily-brief'
      preLoaderRoute: typeof ApiPublicHooksTelegramDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-scan': {
      id: '/api/public/hooks/automation-scan'
      path: '/api/public/hooks/automation-scan'
      fullPath: '/api/public/hooks/automation-scan'
      preLoaderRoute: typeof ApiPublicHooksAutomationScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/proposals/$id': {
      id: '/_authenticated/admin/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/admin/proposals/$id'
      preLoaderRoute: typeof AuthenticatedAdminProposalsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/$id': {
      id: '/_authenticated/admin/leads/$id'
      path: '/leads/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices/$id': {
      id: '/_authenticated/admin/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assistant/$threadId': {
      id: '/_authenticated/admin/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/admin/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAdminAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAdminAssistantRoute
    }
  }
}

interface AuthenticatedAdminAssistantRouteChildren {
  AuthenticatedAdminAssistantThreadIdRoute: typeof AuthenticatedAdminAssistantThreadIdRoute
  AuthenticatedAdminAssistantIndexRoute: typeof AuthenticatedAdminAssistantIndexRoute
}

const AuthenticatedAdminAssistantRouteChildren: AuthenticatedAdminAssistantRouteChildren =
  {
    AuthenticatedAdminAssistantThreadIdRoute:
      AuthenticatedAdminAssistantThreadIdRoute,
    AuthenticatedAdminAssistantIndexRoute:
      AuthenticatedAdminAssistantIndexRoute,
  }

const AuthenticatedAdminAssistantRouteWithChildren =
  AuthenticatedAdminAssistantRoute._addFileChildren(
    AuthenticatedAdminAssistantRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAssistantRoute: typeof AuthenticatedAdminAssistantRouteWithChildren
  AuthenticatedAdminAutomationRoute: typeof AuthenticatedAdminAutomationRoute
  AuthenticatedAdminConversationsRoute: typeof AuthenticatedAdminConversationsRoute
  AuthenticatedAdminMemoryRoute: typeof AuthenticatedAdminMemoryRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminInvoicesIdRoute: typeof AuthenticatedAdminInvoicesIdRoute
  AuthenticatedAdminLeadsIdRoute: typeof AuthenticatedAdminLeadsIdRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminProposalsIdRoute: typeof AuthenticatedAdminProposalsIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
  AuthenticatedAdminInvoicesIndexRoute: typeof AuthenticatedAdminInvoicesIndexRoute
  AuthenticatedAdminLeadsIndexRoute: typeof AuthenticatedAdminLeadsIndexRoute
  AuthenticatedAdminProjectsIndexRoute: typeof AuthenticatedAdminProjectsIndexRoute
  AuthenticatedAdminProposalsIndexRoute: typeof AuthenticatedAdminProposalsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAssistantRoute:
    AuthenticatedAdminAssistantRouteWithChildren,
  AuthenticatedAdminAutomationRoute: AuthenticatedAdminAutomationRoute,
  AuthenticatedAdminConversationsRoute: AuthenticatedAdminConversationsRoute,
  AuthenticatedAdminMemoryRoute: AuthenticatedAdminMemoryRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedAdminPortfolioRoute: AuthenticatedAdminPortfolioRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  AuthenticatedAdminInvoicesIdRoute: AuthenticatedAdminInvoicesIdRoute,
  AuthenticatedAdminLeadsIdRoute: AuthenticatedAdminLeadsIdRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  AuthenticatedAdminProposalsIdRoute: AuthenticatedAdminProposalsIdRoute,
  AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  AuthenticatedAdminInvoicesIndexRoute: AuthenticatedAdminInvoicesIndexRoute,
  AuthenticatedAdminLeadsIndexRoute: AuthenticatedAdminLeadsIndexRoute,
  AuthenticatedAdminProjectsIndexRoute: AuthenticatedAdminProjectsIndexRoute,
  AuthenticatedAdminProposalsIndexRoute: AuthenticatedAdminProposalsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CaraKerjakuMenggunakanAiRoute: CaraKerjakuMenggunakanAiRoute,
  JasaAiAutomationBisnisRoute: JasaAiAutomationBisnisRoute,
  JasaDashboardBisnisRoute: JasaDashboardBisnisRoute,
  JasaPembuatanAplikasiCustomRoute: JasaPembuatanAplikasiCustomRoute,
  JasaPembuatanWebsiteAplikasiLandingPageRoute:
    JasaPembuatanWebsiteAplikasiLandingPageRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  DSlugRoute: DSlugRoute,
  ISlugRoute: ISlugRoute,
  InsightSlugRoute: InsightSlugRoute,
  PortalTokenRoute: PortalTokenRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  InsightIndexRoute: InsightIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiPublicConsultantChatRoute: ApiPublicConsultantChatRoute,
  ApiPublicHooksAutomationScanRoute: ApiPublicHooksAutomationScanRoute,
  ApiPublicHooksTelegramDailyBriefRoute: ApiPublicHooksTelegramDailyBriefRoute,
  ApiPublicPaymentsXenditRoute: ApiPublicPaymentsXenditRoute,
  ApiPublicTelegramTestRoute: ApiPublicTelegramTestRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
